In [23]:
import numpy as np 

In [24]:
import matplotlib as mt


In [25]:
import pandas as pd

NUMPY ARRAY


In [27]:
myNumpyList = [20,30,40]


In [28]:
np.array(myNumpyList)


array([20, 30, 40])

In [29]:
myMatrixList = [[20,40,50,] , [30,40,50] , [10,40,60]]

In [30]:
np.array(myMatrixList)

array([[20, 40, 50],
       [30, 40, 50],
       [10, 40, 60]])

In [31]:
type(myMatrixList)

list

##ARANGE


In [33]:
np.arange


<function numpy.arange>

In [34]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
myArangeList = np.arange(1,10,2)

In [37]:
myArangeList

array([1, 3, 5, 7, 9])

##ZEROS

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

##ONES

In [42]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [43]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

##LINSPACE


In [45]:
np.linspace(0,10,10)


array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [46]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [47]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [48]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

##EYE

In [50]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [51]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [101]:
myNewArray = [1,2,3]

In [103]:
myNewArray = np.array

In [105]:
myNewArray

<function numpy.array>

In [107]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [109]:
myLiST = np.arange(1,10)

In [115]:
myLiST

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
myLiST.max()

9

In [119]:
myLiST.min()

1

In [121]:
myLiST.argmax()

8

In [123]:
myLiST.argmin()

0

In [125]:
myLiST.shape(3,3)

TypeError: 'tuple' object is not callable

In [127]:
myLiST.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
myNumpyList = np.arange(0,31)

In [131]:
myNumpyList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [137]:
np.random.randn(1,10,5)

array([[[-0.29940523, -0.11163594, -1.6195153 , -0.92938536,
          0.27527279],
        [-0.78626343, -0.70574368,  0.07052809, -0.87951336,
         -0.25865795],
        [ 1.37482329, -0.41745906, -0.63963579,  0.20241211,
         -0.3863526 ],
        [ 1.25271399, -0.95767048, -0.33844622, -1.79106872,
          2.15919221],
        [-0.25948849, -0.73168914, -0.73656089,  0.29738423,
         -0.27575644],
        [ 2.08320567, -0.58123518,  1.03414477,  0.96404072,
          0.26517946],
        [-0.08175978,  0.86384511,  0.00309016, -1.95180153,
         -1.54222789],
        [ 0.25143722, -0.53874286, -0.23469415,  0.30950752,
          0.31128756],
        [-0.30247457,  0.04834943, -0.73759443, -2.83571288,
          1.83180325],
        [-0.01469051, -0.76313497,  0.25225375, -0.57488901,
         -0.51727058]]])

In [139]:
myRandom = np.random.randn(1,10,1)

In [141]:
myRandom

array([[[-1.91197585],
        [ 1.75313607],
        [-0.10833244],
        [ 1.66233626],
        [ 1.31960252],
        [-1.58820066],
        [-0.67187659],
        [ 0.20566539],
        [ 1.27312632],
        [-0.13295799]]])

In [149]:
myRandomInt = np.random.randint(1,30,5)

In [151]:
myRandomInt

array([15, 12, 13,  2,  8])

In [153]:
myRandomInt = np.random.randn()

In [155]:
myRandomInt

1.254270524693444

In [157]:
np.random.randn(4)

array([-0.18567649,  1.44381804,  0.39871462,  0.15580356])

In [159]:
np.random.randn(4,4)

array([[-1.38042887, -0.15367335, -0.70849489,  0.05138664],
       [-1.4343879 , -0.43084489, -0.54812102,  0.5965372 ],
       [-0.39623218, -1.76522008, -0.39737706, -0.54691792],
       [ 0.11755566, -0.79306217, -1.16799952,  0.50514633]])

In [165]:
np.random.randint(1,10)

2